[project]
authors = [
  { name = "Joshua Price", email = "jprice4@snapchat.com" },
]
dependencies = [
  "dash>=3.2.0",
  "mplcursors>=0.7",
  "numpy",
  "opencv-python>=4.11.0.86",
  "pillow",
  "scikit-learn>=1.8.0",
  "torch",
  "torchvision>=0.25.0",
  "tqdm>=4.67.3",
]
description = "A simple python package to perform inline artefact detection on test station images"
license = { file = "LICENSE" }
name = "aria"
readme = "README.md"
requires-python = ">3.12"
version = "1.0.0"

[project.scripts]
test = "pytest:main"

[dependency-groups]
dev = [
  "basedmypy",
  "git-lfs>=1.6",
  "matplotlib==3.10.1",
  "openpyxl==3.0.9",
  "pandas>=2.2.0,<3.0.0",
  "pip-audit",
  "pydoctor",
  "pytest",
  "pytest-cov>=6.2.1",
  "ruff",
]

[tool.uv]
default-groups = ["dev"]
index-url = "https://registry.snapchat.com/python/virtual/"
native-tls = true

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["aria"]

[tool.mypy]
exclude = [".venv"]
files = ["."]

[tool.pydoctor]
add-package = ["ada-beta"]
docformat = "google"
html-output = "site"
make-html = true
project-name = "ada-beta"
template-dir = ["pydoctor_assets/assets"]
verbose = true

[tool.pytest.ini_options]
addopts = [
  "--disable-warnings",
  "--strict-markers",
  "--tb=short",
  "-v",
]
markers = [
  "integration: marks tests as integration tests",
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
python_classes = ["Test*"]
python_files = ["*_test.py", "test_*.py"]
python_functions = ["test_*"]
testpaths = ["tests"]
